### ISSUE TITLE
Index has already been checked

### ISSUE THREAD

**Issue by tylerbhughes** [htmllint/grunt-htmllint#12]
I get an error message stating `Fatal error: Cannot get options for index 6937 when index 6937 has already been checked`. I've got the following configuration in my grunt file.

```
htmllint: {
      options: { },
      src: [ '*.html', 'examples/**/*.html']
    },  
```

Did I do something wrong in my configuration?

**Comment by RandomlyKnighted** [comment]
Ok, so I did some testing and apparently

```
htmllint: {
      options: { },
      src: [ 'examples/**/*.html']
    }, 
```

works, but

```
htmllint: {
      options: { },
      src: [ '*.html']
    }, 
```
does not. Can you not search the same directory as the gruntfile or is there something else wrong with my configuration?

cc: @coalman

**Comment by ben-burlingham** [comment]
I'm getting the same error with the following config:

    options: {
        force: true,
        // opts: { maxerr: 5 },
        'attr-quote-style': "double",
        'attr-name-style': 'dash',
        'class-style': 'dash',
        'id-class-style': 'dash'
    },

    src: [
        'public/<%= app %>/**/*.html',
        'public/common/views/*.html'
    ],

**Comment by tomvonclef** [comment]
I'm running into this issue as well: `[htmllint error in templates/led-driver.html ] Error: Cannot get options for index 4429 when index 4429 has already been checked`. Not sure what it is, but this file probably contains an error..

**Comment by tomvonclef** [comment]
I isolated the issue. There was `</br>` in the HTML instead of `<br/>`. I fixed it and the `htmllint error` went away.

**Comment by b3wii** [comment]
I get a similar error when h4 is child of p:

Fatal error: Cannot get options for index 4130 when index 4130 has already been checked

**Comment by mlochbaum** [comment]
There are a few issues for this in the htmllint project; some have been fixed. See https://github.com/htmllint/htmllint/issues/161, https://github.com/htmllint/htmllint/issues/175, and https://github.com/htmllint/htmllint/issues/176.
