### ISSUE TITLE
Trying to leverage attr-name-ignore-regex inside a .htmllintrc

### ISSUE THREAD

**Issue by ArnaudBuchholz** [htmllint/grunt-htmllint#16]
Guys,

I would need some help to make it work as I didn't find the proper way to ignore a specific attribute name.
Currently, my .htmllintrc file looks like this:

``` javascript
{
    "attr-name-ignore-regex": "{}"
}
```

and the html contains:

``` html
                        <td><input type="checkbox" {}="if ($item.doc) { return 'checked=\'true\''; } else return '';"></td>
```

It results in:

> > sources.html: (E002), line 54, col 51, attribute names must match the format: lowercase

What am I doing wrong?

**Comment by mlochbaum** [comment]
This works in htmllint 0.7.2, which is used by grunt-htmllint 0.3.0. If you still care after almost two years, try it with the new version.

**Comment by ArnaudBuchholz** [comment]
Thanks, I will check it
