### ISSUE TITLE
please update htmlhint to 0.2.7

### ISSUE THREAD

**Issue by bonesoul** [htmllint/grunt-htmllint#18]
https://github.com/htmllint/htmllint/releases/tag/v0.2.7

**Comment by henrahmagix** [comment]
This already works: `^0.2.4` in semver allows `0.2.7` to be installed, but no greater.

**Comment by mlochbaum** [comment]
Skipped to 0.7.2. Same numbers, anyway.

**Comment by bonesoul** [comment]
:D
