### ISSUE TITLE
npm WARN grunt-htmllint@0.2.7 requires a peer of grunt@~0.4.5 but none was installed.

### ISSUE THREAD

**Issue by jitendravyas** [htmllint/grunt-htmllint#21]
I get this warning

`npm WARN grunt-htmllint@0.2.7 requires a peer of grunt@~0.4.5 but none was installed.`

**Comment by paolo-tanium** [comment]
:+1:

**Comment by mlochbaum** [comment]
This was probably fixed when I jumped all the dependencies forward a few years.
